### ISSUE TITLE
Some source code was missed

### ISSUE THREAD

**Issue by yeren66** [EngineeringSoftware/codeditor#1]
When attempting to run the command
```
python -m deltr.coditT5.CodeT5 fit --exp_dir models/edit-translation/java2cs --data.dataset java2cs --data.model edit-translation --config configs/coditT5.yaml
```
an error occurred. Within the CodeT5.py file at line 31, it attempts to import compute_bleu_scores using
```
from deltr.eval.evaluate import compute_bleu_scores
However, no eval directory exists within the deltr directory.
```
Upon reviewing your paper, I noted the mention of the coditT5 model and hypothesized the missing file might have been overlooked in the repository. Fortunately, I located the necessary file and, after making minor adjustments, placed it within the codeditor. Subsequently, I encountered another issue:
```
(cdt) ----------------------------------------------------------------------------------------------------------
~/codeditor/python (public*) » python -m deltr.coditT5.CodeT5 fit --exp_dir models/edit-translation/java2cs --data.dataset java2cs --data.model edit-translation --config  configs/coditT5.yaml
Traceback (most recent call last):
  File "/home/yeren/miniconda3/envs/cdt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yeren/miniconda3/envs/cdt/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yeren/codeditor/python/deltr/coditT5/CodeT5.py", line 451, in <module>
    DefaultLightningCLI(
  File "/home/yeren/codeditor/python/deltr/coditT5/utils.py", line 54, in __init__
    super().__init__(*args, **kwargs)
  File "/home/yeren/miniconda3/envs/cdt/lib/python3.8/site-packages/seutil/../pytorch_lightning/utilities/cli.py", line 515, in __init__
    self.setup_parser(run, main_kwargs, subparser_kwargs)
  File "/home/yeren/miniconda3/envs/cdt/lib/python3.8/site-packages/seutil/../pytorch_lightning/utilities/cli.py", line 551, in setup_parser
    self._add_subcommands(self.parser, **subparser_kwargs)
  File "/home/yeren/miniconda3/envs/cdt/lib/python3.8/site-packages/seutil/../pytorch_lightning/utilities/cli.py", line 624, in _add_subcommands
    subcommand_parser = self._prepare_subcommand_parser(trainer_class, subcommand, **kwargs.get(subcommand, {}))
  File "/home/yeren/miniconda3/envs/cdt/lib/python3.8/site-packages/seutil/../pytorch_lightning/utilities/cli.py", line 632, in _prepare_subcommand_parser
    self._add_arguments(parser)
  File "/home/yeren/miniconda3/envs/cdt/lib/python3.8/site-packages/seutil/../pytorch_lightning/utilities/cli.py", line 589, in _add_arguments
    self.add_arguments_to_parser(parser)
  File "/home/yeren/codeditor/python/deltr/coditT5/utils.py", line 120, in add_arguments_to_parser
    parser.add_lr_scheduler_args(types, nested_key, link_to)
  File "/home/yeren/miniconda3/envs/cdt/lib/python3.8/site-packages/seutil/../pytorch_lightning/utilities/cli.py", line 213, in add_lr_scheduler_args
    self.add_subclass_arguments(lr_scheduler_class, nested_key, **kwargs)
  File "/home/yeren/miniconda3/envs/cdt/lib/python3.8/site-packages/jsonargparse/_signatures.py", line 506, in add_subclass_arguments
    raise ValueError(f"Expected 'baseclass' argument to be a class or a tuple of classes: {baseclass}")
ValueError: Expected 'baseclass' argument to be a class or a tuple of classes: ()
```
Unsure if my actions contributed to this problem, I cloned coditT5 to attempt fine-tuning, only to face the same error. Your assistance in resolving this would be greatly appreciated.

**Comment by JiyangZhang** [comment]
Hi,

Do you still have this problem? I am so sorry that I missed your issue. Please send me email if you have further question!
